#!/usr/bin/env bash
# Install nginx web server

apt-get -y update
apt-get -y install nginx

service nginx start

ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

service nginx restart
