#!/usr/bin/env bash
# Install nginx web server

apt-get -y update
apt-get -y install nginx

# Nginx listening on port 80
sed -i 's/listen [::]:80 default_server;/listen 80;/g' /
/etc/nginx/sites-available/default

cat <<EOF > /var/www/html/index.html
Hello World!
EOF

service nginx restart
