#!/usr/bin/env bash
# Installs and configure web server to redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

sh -c "echo 'Hello World!' > /var/www/html/index.html"

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@ikechindukwe4161/featured permanent;' /etc/nginx/sites-available/default

service nginx restart
