#!/usr/bin/env bash
# use while loop to print 'Best School' 10 times but
# on the 4th loop, print 'bad luck' and on
# the 8th loop, print 'good luck'
i=1
while [ $i -le 9 ]
do
    if [ $i -eq 4 ]
    then
	echo 'bad luck'

    elif [ $i -eq 8 ]
    then
	echo 'good luck'
    fi

    echo 'Best School'
    ((i++))
done
