#!/usr/bin/env bash
# Displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed
# using the for loop

dir_list=$(ls)
for i in $dir_list
do
    echo "$i" | cut -d '-' -f2
done
