#!/usr/bin/env bash
# Block all incoming traffic but

sudo apt-get update
sudo apt install -y ufw

sudo ufw default allow outgoing
sudo ufw default deny incoming

# Allow SSH
sudo ufw allow 22

# Allow HTTPS SSL
sudo ufw allow 443

# Allow HTTP
sudo ufw allow 80

echo 'y' | sudo ufw enable
